### PR TITLE
Set drawer to STATE_CLOSED when dragged fully closed.

### PR DESCRIPTION
**Pull request by forrestpangborn**
When dragging drawer fully closed, state is never set back to STATE_CLOSED.  This becomes particularly problematic when the touch mode is TOUCH_MODE_NONE because toggleMenu() will not open the drawer.  This change sets the state to STATE_CLOSED when the menu is no longer visible in setOffsetPixels().

### CODE REVIEW

**Comment by SimonVT** [comment]
Does up events not trigger animateOffsetTo? If the delta is 0, the state should be set to closed.
Also, please submit the pull request against the dev branch.

**Comment by forrestpangborn** [comment]
onUpEvent() isn't called in this case.  The if at the top of onTouchEvent() causes a return prior to entering the switch on the event's action value.  mMenuVisible is set to false on the ACTION_MOVE event (which occurs prior to the ACTION_UP in this case) to the edge.  A different fix could be to remove that if, but I'm not sure if that would introduce other problems.

If this fix is fine, let me know and I'll resubmit to the dev branch.

**Comment by SimonVT** [comment]
Ah, I see. Nicely spotted. I think the right way to handle this is to not return in the first if when mIsDragging is true. With your patch, the user could still be dragging even if the offset hits 0 at some point, but the state would stay at CLOSED until the drag is released.

**Comment by forrestpangborn** [comment]
That definitely seems like a better idea.  I can make that change to VerticalDrawer and HorizontalDrawer and resubmit if you'd like.

**Comment by SimonVT** [comment]
Feel free :)

**Comment by forrestpangborn** [comment]
Don't need this one anymore.  Thanks!

**Pull request closed without merging**
