### PR TITLE
Add TOUCH_MODE_ACTIONBAR

### PR DESCRIPTION
**Pull request by lexer**
This is a custom touch mode that allows open sliding menu only by sliding of actionbar.

I have also provided sample activity to test this.

Im open to any suggestion how to improve the code to fit your styles and guidelines.

### CODE REVIEW

**Comment by SimonVT** [comment]
I like the idea, but implementing it is a bit more tricky than this.

The status bar and action bar heights can't be hardcoded. For example, the status bar might not even be there. That part is fairly easy to solve, tho. `View#fitSystemWindows(Rect)` can be used to get the top offset (I already do this for the menu when wrapping the window).

The action bar is a bit more tricky. First off, the height of the action bar changes based on device size and configuration. On HC+ this could be solved by reading `?android:attr/actionBarSize` from the theme. The problem with this is that it'd break compatibility with ActionBarSherlock. We could introduce a dependency on ABS, but I think that would be a bad idea.

A second solution could be to get a reference to `android.R.id.content` and use `ViewGroup#offsetDescendantRectToMyCoords(View, Rect)` to get its position relative to the drawer. The content should be positioned below the action bar.. Except when using action bar overlay..

I think the way to go is to add a theme attribute that lets the user set the height of the touch area manually. They can then use `?android:attr/actionBarSize` on HC+, and `?attr/actionBarSize` if they use ABS, or whatever size they desire.

**Comment by lexer** [comment]
Ok. I like the idea of using theme attribute. 

@SimonVT I see travis error, but doesn't see tests in this project.

**Comment by JakeWharton** [comment]
Travis CI is broken for Android projects at the moment. You also need to open this pull request against the `dev` branch.

**Comment by lexer** [comment]
@JakeWharton Yep, will fix this.

**Comment by lexer** [comment]
Close request to resubmit it to dev.

**Pull request closed without merging**
