### PR TITLE
Extended drop shadow modifiers

### PR DESCRIPTION
**Pull request by DHuckaby**

### CODE REVIEW

**Comment by SimonVT** [comment]
Thanks for the contribution.
Please rename it setDropShadow, add one that takes a resource id, add a getter and move the implementation up to MenuDrawer.

**Comment by DHuckaby** [comment]
Their is no getDropShadowColor so that would be inconsistent. I think if you wanted it to be consistent adding a setDropShadowResource(int resId) would work better. (Which is out of scope of this pull request)

**Comment by SimonVT** [comment]
There's no View#getBackgroundColor either. Adding a method for setting the drop shadow from a resource is not out of scope for a pull request that makes it possible to set a custom drawable.

**Comment by SimonVT** [comment]
There should probably also be a style attribute for this, that takes precedence over mdDropShadowColor.

**Comment by DHuckaby** [comment]
I don't see any other pending issues, do you have an eta on when this will be merged?

**Comment by SimonVT** [comment]
When I decide on what naming I'll go with.

**Comment by SimonVT** [comment]
Rename the methods to setDropShadow(Drawable|int) and getDropShadow(), and rename the theme attribute to mdDropShadow. Then squash it into a single commit. Then I'll get it merged.

**Comment by SimonVT** [comment]
Thanks :)

**Pull request merged**
