### PR TITLE
handle the case where findPointerIndex does not find a valid index

### PR DESCRIPTION
**Pull request by bhurling**
There are cases where findPointerIndex does not find a valid index in the onInterceptTouchEvent method.

### CODE REVIEW

**Comment by SimonVT** [comment]
When does this happen? I'm not sure I'm interested in just hiding an issue.

**Comment by Tolriq** [comment]
Looks like the same problem as #131 and #125. (#131 handles way more cases, still not sure all)

According to the doc : 
findPointerIndex  - Returns either the index of the pointer (for use with getX(int) et al.), or -1 if there is no data available for that pointer identifier.

So -1 should be handled and while I get numerous reports on crash about it I'm still unable to reproduce and get more  details on the cases to when it triggers.

**Comment by SimonVT** [comment]
I don't necessarily agree that a pointer index of -1 should be handled. mActivePointerId should be updated as pointers enter and leave the screen. `findPointerIndex` returning -1 suggests that that's not happening in some cases. I'm more interested in a solution to that issue.

**Comment by izacus** [comment]
Note, this issue tends to be easier to reproduce if user attempts to use two-or-more touches on the screen instead of a single touch.

**Pull request closed without merging**
